import json
import os

# Updated Simulation Code with Aggressive Strategy
CODE_SIM_AGGRESSIVE = [
    "# 예측 함수\n",
    "def predict_with_prob(model, loader):\n",
    "    model.eval()\n",
    "    probs = []\n",
    "    with torch.no_grad():\n",
    "        for batch_X, _ in loader:\n",
    "            batch_X = batch_X.to(device)\n",
    "            out = model(batch_X)\n",
    "            probs.append(out.cpu().numpy())\n",
    "    return np.vstack(probs).flatten()\n",
    "\n",
    "# 테스트 셋 예측 수행\n",
    "my_prob = predict_with_prob(my_model, test_loader)\n",
    "\n",
    "# 시뮬레이션용 데이터 준비\n",
    "test_start_idx = len(btc_features) - len(y_test) + sequence_length\n",
    "test_prices = btc_features['Close'].iloc[test_start_idx:test_start_idx+len(my_prob)].values\n",
    "test_dates = btc_features.index[test_start_idx:test_start_idx+len(my_prob)]\n",
    "\n",
    "# 보조 지표 준비 (RSI, MACD)\n",
    "test_rsi = btc_features['RSI_14'].iloc[test_start_idx:test_start_idx+len(my_prob)].values\n",
    "test_macd = btc_features['MACD'].iloc[test_start_idx:test_start_idx+len(my_prob)].values\n",
    "test_macd_sig = btc_features['MACD_Signal'].iloc[test_start_idx:test_start_idx+len(my_prob)].values\n",
    "\n",
    "# 변동성 데이터\n",
    "test_volatility = btc_features['Volatility_10'].iloc[test_start_idx:test_start_idx+len(my_prob)].values\n",
    "volatility_threshold = np.percentile(test_volatility, 90) # 상위 10%만 피함 (공격적)\n",
    "\n",
    "# 공격적 하이브리드 전략 시뮬레이션\n",
    "def simulate_custom_strategy(probs, prices, dates, rsi, macd, macd_sig, volatilities, vol_thresh, initial_capital=10000):\n",
    "    cash = initial_capital\n",
    "    btc = 0\n",
    "    tx_fee = 0.001\n",
    "    history = []\n",
    "    trade_log = []\n",
    "    \n",
    "    # 파라미터 : 거래 활성화를 위해 임계값 대폭 낮춤\n",
    "    BUY_THRESH = 0.50    # 50% 이상이면 매수 검토\n",
    "    SELL_THRESH = 0.40   # 40% 미만이면 매도 검토\n",
    "    \n",
    "    for i in range(len(probs)):\n",
    "        prob = probs[i]\n",
    "        price = prices[i]\n",
    "        vol = volatilities[i]\n",
    "        r_val = rsi[i]\n",
    "        m_val = macd[i]\n",
    "        m_sig = macd_sig[i]\n",
    "        \n",
    "        portfolio_val = cash + btc * price\n",
    "        \n",
    "        # 마지막 날 전량 매도\n",
    "        if i == len(probs) - 1:\n",
    "            if btc > 0:\n",
    "                cash += btc * price * (1 - tx_fee)\n",
    "                btc = 0\n",
    "            history.append(cash)\n",
    "            continue\n",
    "            \n",
    "        # 1. 기본 타겟 비중 계산 (확률 기반)\n",
    "        # (Prob - 0.4) * 2 => 0.4일때 0, 0.9일때 1.0\n",
    "        raw_ratio = (prob - 0.4) * 2.0\n",
    "        target_ratio = min(max(raw_ratio, 0.0), 1.0)\n",
    "        \n",
    "        # 2. 보조 지표 보정 (RSI & MACD)\n",
    "        # RSI < 30 (과매도) -> 강제 매수 신호 (비중 +0.3)\n",
    "        if r_val < 30:\n",
    "            target_ratio = max(target_ratio, 0.3)\n",
    "            target_ratio += 0.2\n",
    "            \n",
    "        # RSI > 70 (과매수) -> 비중 축소\n",
    "        if r_val > 70:\n",
    "            target_ratio *= 0.5\n",
    "            \n",
    "        # MACD 골든크로스 상태 (MACD > Signal) -> 비중 확대\n",
    "        if m_val > m_sig:\n",
    "            target_ratio *= 1.2\n",
    "            # 최소 10%는 가져가도록\n",
    "            if target_ratio < 0.1: target_ratio = 0.1\n",
    "        else:\n",
    "            # 데드크로스 -> 비중 축소\n",
    "            target_ratio *= 0.8\n",
    "            \n",
    "        # 3. 리스크 관리 (초고변동성만 회피)\n",
    "        if vol > vol_thresh:\n",
    "            target_ratio *= 0.5\n",
    "            \n",
    "        # 최종 비중 클리핑 0~1\n",
    "        target_ratio = min(max(target_ratio, 0.0), 1.0)\n",
    "            \n",
    "        # 4. 리밸런싱\n",
    "        target_btc_val = portfolio_val * target_ratio\n",
    "        current_btc_val = btc * price\n",
    "        diff = target_btc_val - current_btc_val\n",
    "        \n",
    "        # 거래 실행\n",
    "        if diff > 0: # 매수\n",
    "            # 10달러 이상일 때만 거래\n",
    "            if diff > 10:\n",
    "                amount_to_buy_usd = diff\n",
    "                if amount_to_buy_usd > cash: amount_to_buy_usd = cash\n",
    "                if amount_to_buy_usd > 0:\n",
    "                    btc_bought = (amount_to_buy_usd * (1 - tx_fee)) / price\n",
    "                    btc += btc_bought\n",
    "                    cash -= amount_to_buy_usd\n",
    "                    trade_log.append({'date': dates[i], 'action': 'BUY', 'price': price, 'value': amount_to_buy_usd})\n",
    "        elif diff < 0: # 매도\n",
    "            if -diff > 10:\n",
    "                amount_to_sell_usd = -diff\n",
    "                amount_to_sell_btc = amount_to_sell_usd / price\n",
    "                if amount_to_sell_btc > btc: amount_to_sell_btc = btc\n",
    "                if amount_to_sell_btc > 0:\n",
    "                    cash_gained = amount_to_sell_btc * price * (1 - tx_fee)\n",
    "                    cash += cash_gained\n",
    "                    btc -= amount_to_sell_btc\n",
    "                    trade_log.append({'date': dates[i], 'action': 'SELL', 'price': price, 'value': cash_gained})\n",
    "            \n",
    "        history.append(cash + btc * price)\n",
    "\n",
    "    total_return = (history[-1] - initial_capital) / initial_capital * 100\n",
    "    \n",
    "    return {\n",
    "        'initial_capital': initial_capital,\n",
    "        'final_value': history[-1],\n",
    "        'total_return': total_return,\n",
    "        'portfolio_values': history,\n",
    "        'num_trades': len(trade_log),\n",
    "        'total_fees_paid': 0 # Simplified\n",
    "    }\n",
    "\n",
    "# 시뮬레이션 실행\n",
    "my_result = simulate_custom_strategy(\n",
    "    probs=my_prob,\n",
    "    prices=test_prices,\n",
    "    dates=test_dates,\n",
    "    rsi=test_rsi,\n",
    "    macd=test_macd,\n",
    "    macd_sig=test_macd_sig,\n",
    "    volatilities=test_volatility,\n",
    "    vol_thresh=volatility_threshold\n",
    ")\n",
    "\n",
    "print(\"=\"*70)\n",
    "print(\"🚀 나의 트레이딩 전략 결과 (Aggressive Hybrid)\")\n",
    "print(\"=\"*70)\n",
    "print(f\"초기 자본: ${my_result['initial_capital']:,.2f}\")\n",
    "print(f\"최종 자본: ${my_result['final_value']:,.2f}\")\n",
    "print(f\"수익률: {my_result['total_return']:.2f}%\")\n",
    "print(f\"거래 횟수: {my_result['num_trades']}회\")\n",
    "print(\"=\"*70)"
]

# Updated Design Description to match Aggressive Strategy
DESIGN_DESC_AGGRESSIVE = [
    "## 5. 자신만의 모델 및 전략 개발 ⭐\n",
    "\n",
    "### 📝 개발 가이드\n",
    "\n",
    "#### 1. 모델 개선 아이디어\n",
    "- **아키텍처**: LSTM → GRU, Transformer, CNN+LSTM, Attention\n",
    "- **하이퍼파라미터**: hidden_size, dropout, learning_rate\n",
    "- **앙상블**: 여러 모델의 예측 결합\n",
    "\n",
    "#### 2. 전략 개선 아이디어\n",
    "- **임계값 조정**: threshold를 0.6 또는 0.7로 높여 신뢰도 높은 거래만\n",
    "- **포지션 크기**: 확률 × 2 - 1 (예: 70% → 40% 투자)\n",
    "- **리스크 관리**: 최대 손실 한도, 이동평균선 활용\n",
    "- **복합 전략**: 모델 예측 + RSI + MACD 결합\n",
    "\n",
    "---\n",
    "\n",
    "**TODO: 아래에 자신의 모델 설계 설명을 작성하세요**\n",
    "\n",
    "```\n",
    "1. 모델 아키텍처: **RobustGRU**\n",
    "   - 2층 GRU 구조 (Hidden Size: 128 -> 64)\n",
    "   - 모델 강건성 확보를 위해 Dropout(0.3) 및 Batch Normalization 적용\n",
    "\n",
    "2. 선택 이유:\n",
    "   - GRU는 LSTM 대비 학습이 빠르고 데이터가 적은 금융 시계열에 적합\n",
    "   - 단순 벤치마크 모델보다 복잡한 패턴을 학습할 수 있도록 레이어 깊이를 늘림\n",
    "\n",
    "3. 트레이딩 전략: **Aggressive Hybrid (Model + RSI + MACD)**\n",
    "   - **핵심 아이디어**: 하락장에서도 기술적 반등(Rebound)을 노리기 위해 기술적 지표를 적극 활용\n",
    "   - **1. 모델 확신도**: 매수 임계값을 0.5로 대폭 낮추어 거래 기회를 늘림\n",
    "   - **2. RSI 보정**: RSI 30 미만(과매도) 구간에서는 모델 예측이 낮아도 강제 매수 신호 발생 (역추세 매매)\n",
    "   - **3. MACD 필터**: 골든크로스(MACD > Signal) 상태일 때 비중 20% 확대\n",
    "   - **4. 리밸런싱**: 확률 및 지표에 따라 매일 투자 비중을 동적으로 조절\n",
    "\n",
    "4. 하이퍼파라미터:\n",
    "   - BUY_Threshold: 0.50 (공격적)\n",
    "   - RSI_Oversold: 30\n",
    "   - Volatility_Filter: 상위 10% 변동성만 회피\n",
    "\n",
    "5. 예제와의 차별점:\n",
    "   - 예제는 단순히 확률만 보고 거래하지만, 이 전략은 RSI와 MACD를 결합하여 모델이 놓칠 수 있는 기술적 매매 타이밍을 포착함\n",
    "   - 거래가 없는(0 Trades) 상황을 방지하기 위해 진입 장벽을 낮추고 보조 지표로 보완하는 하이브리드 전략 사용\n",
    "```"
]

nb_path = "c:\\AI\\FinalProject\\TimeSeriesForecastingTest\\assignment_notebook.ipynb"

with open(nb_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

modified_count = 0
for cell in nb["cells"]:
    source_str = "".join(cell["source"])
    
    # Replace Simulation Code
    if "# 예측 함수" in source_str and "def predict_with_prob" in source_str:
        # Check if it's the simulation cell we want to replace (contains simulate_custom_strategy)
        # Note: We replaced it before, so look for unique markers or just replacing the Simulation Cell we tagged previously
        if "simulate_custom_strategy" in source_str: 
             print("Found Simulation Cell -> Updating to Aggressive Strategy")
             cell["source"] = CODE_SIM_AGGRESSIVE
             modified_count += 1
    
    # Replace Design Description
    elif "TODO: 아래에 자신의 모델 설계 설명" in source_str:
        print("Found Design Description -> Updating to Aggressive Description")
        cell["source"] = DESIGN_DESC_AGGRESSIVE
        modified_count += 1

if modified_count >= 2:
    with open(nb_path, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    print(f"Notebook updated with aggressive strategy. Modified bits: {modified_count}")
else:
    print("Warning: Cells not found or already updated.")
